// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGh2Pg2Z38gQrep36HEtQathukCOkiurQ',
    appId: '1:151402684339:web:6acc72b49353f21954f5c6',
    messagingSenderId: '151402684339',
    projectId: 'shfayi',
    authDomain: 'shfayi.firebaseapp.com',
    storageBucket: 'shfayi.appspot.com',
    measurementId: 'G-KP1LFNPJ0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaicw-lVmMO-cjI9c5_-frskpErF-g4rw',
    appId: '1:151402684339:android:9aa469e4e2533c2954f5c6',
    messagingSenderId: '151402684339',
    projectId: 'shfayi',
    storageBucket: 'shfayi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE8m2uRqaNhDH7F9KaUtcOz8O19n6UPOI',
    appId: '1:151402684339:ios:89ff2ee47a2a4b3f54f5c6',
    messagingSenderId: '151402684339',
    projectId: 'shfayi',
    storageBucket: 'shfayi.appspot.com',
    iosClientId:
        '151402684339-e90gchmq917t9n6mtn6jdsnb4q6ptjmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shifayiy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE8m2uRqaNhDH7F9KaUtcOz8O19n6UPOI',
    appId: '1:151402684339:ios:89ff2ee47a2a4b3f54f5c6',
    messagingSenderId: '151402684339',
    projectId: 'shfayi',
    storageBucket: 'shfayi.appspot.com',
    iosClientId:
        '151402684339-e90gchmq917t9n6mtn6jdsnb4q6ptjmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shifayiy',
  );
}
